name: Compilar aplicación Java

on:
  push:
    branches: [main]
  pull_request:

jobs:
  compilar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Compilar con Maven
        run: mvn --batch-mode --no-transfer-progress clean package
